datagrid:
    website-grid:
        source:
            type: orm
            acl_resource: oro_tracking_website_view
            query:
                select:
                    - website.id
                    - website.identifier
                    - website.url
                    - owner.id as ownerId
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - website.createdAt
                    - website.updatedAt
                from:
                    - { table: %oro_tracking.tracking_website.class%, alias: website }
                join:
                    left:
                        - { join: website.owner, alias: owner }
        columns:
            identifier:
                label: oro.tracking.tracking_website.identifier.label
            url:
                type: twig
                label: oro.tracking.tracking_website.url.label
                frontend_type: html
                template: OroTrackingBundle:TrackingWebsite:Property/url.html.twig
            ownerName:
                type: twig
                label: oro.tracking.tracking_website.owner.label
                frontend_type: html
                template: OroTrackingBundle:TrackingWebsite:Property/owner.html.twig
            createdAt:
                label:   oro.tracking.tracking_website.created_at.label
                frontend_type: datetime
            updatedAt:
                label:   oro.tracking.tracking_website.updated_at.label
                frontend_type: datetime
        sorters:
            columns:
                identifier:
                    data_name: website.identifier
                url:
                    data_name: website.url
                ownerName:
                    data_name: website.ownerName
                createdAt:
                    data_name: website.createdAt
                updatedAt:
                    data_name: website.updatedAt
            default:
                identifier: ASC
        filters:
            columns:
                identifier:
                    type:      string
                    data_name: website.identifier
                url:
                    type:      string
                    data_name: website.url
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: website.createdAt
                updatedAt:
                    type:      datetime
                    data_name: website.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_tracking_website_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_tracking_website_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_tracking_website
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_tracking_website_view
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_tracking_website_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_tracking_website_delete
                label:         Delete
                icon:          trash
                link:          delete_link
